name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    #strategy:
    #  matrix:
    #    node-version: [16.x]
    #    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: GitHub Action for Bash
      # You may pin to the exact commit or the version.
      # uses: lafernando/github-action-bash@50aaa1a696ff3b029db96ae429a4de147a3ce9bd
      uses: lafernando/github-action-bash@v1.0
